name: Keep Render Awake

on:
  schedule:
    - cron: '*/5 * * * *'  # 每 5 分鐘執行一次
  workflow_dispatch:  # 允許手動觸發

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Service
        run: |
          curl -s -o /dev/null -w "%{http_code}" https://cwa-site.onrender.com || echo "Server is down"
